/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Room */
        post: operations["create_room_api_v1_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{room_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room Snapshot */
        get: operations["get_room_snapshot_api_v1_rooms__room_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{room_code}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Room */
        post: operations["join_room_api_v1_rooms__room_code__participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardSnapshot */
        CardSnapshot: {
            /** Count */
            count: number;
            /**
             * Fruit
             * @enum {string}
             */
            fruit: "banana" | "strawberry" | "lemon" | "grape";
        };
        /** CreateRoomRequest */
        CreateRoomRequest: {
            /** Credentialverifier */
            credentialVerifier: string;
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "easy" | "normal" | "hard";
            /** Durationsec */
            durationSec: number;
            /** Name */
            name: string;
            /** Tableseatcount */
            tableSeatCount: number;
            /** Targethumanparticipantcount */
            targetHumanParticipantCount: number;
        };
        /** EntryRequest */
        EntryRequest: {
            /** Credentialverifier */
            credentialVerifier: string;
            /** Name */
            name: string;
        };
        /** EntryResult */
        EntryResult: {
            /** Roomcode */
            roomCode: string;
            snapshot: components["schemas"]["RoomSnapshot"];
        };
        /** MatchResult */
        MatchResult: {
            /** Participants */
            participants: components["schemas"]["ParticipantScore"][];
            /** Score */
            score: number;
            /** Winnerseatindex */
            winnerSeatIndex: number;
        };
        /** ParticipantScore */
        ParticipantScore: {
            /** Correcthits */
            correctHits: number;
            /** Missedhits */
            missedHits: number;
            /** Score */
            score: number;
            scoreBreakdown: components["schemas"]["ScoreBreakdown"];
            /** Seatindex */
            seatIndex: number;
            /** Wronghits */
            wrongHits: number;
        };
        /** ParticipantSnapshot */
        ParticipantSnapshot: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Name */
            name: string;
            /**
             * Ready
             * @default false
             */
            ready: boolean;
            /** Seatindex */
            seatIndex: number;
        };
        /** ProblemDetails */
        ProblemDetails: {
            /** Code */
            code: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** RevealSnapshot */
        RevealSnapshot: {
            /** Seatindex */
            seatIndex: number;
            /** Sequence */
            sequence: number;
        };
        /** RoomConfiguration */
        RoomConfiguration: {
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "easy" | "normal" | "hard";
            /** Durationsec */
            durationSec: number;
            /** Tableseatcount */
            tableSeatCount: number;
            /** Targethumanparticipantcount */
            targetHumanParticipantCount: number;
        };
        /** RoomSnapshot */
        RoomSnapshot: {
            /** Allowedcommands */
            allowedCommands?: ("ready" | "start" | "bell" | "leave" | "forfeit" | "continue" | "post_match_leave")[];
            /**
             * Bellavailable
             * @default false
             */
            bellAvailable: boolean;
            /** Bellfruit */
            bellFruit?: ("banana" | "strawberry" | "lemon" | "grape") | null;
            configuration: components["schemas"]["RoomConfiguration"];
            /** Currentturnseatindex */
            currentTurnSeatIndex?: number | null;
            /** Lastevent */
            lastEvent?: ("correct_bell" | "wrong_bell" | "missed_bell") | null;
            lastReveal?: components["schemas"]["RevealSnapshot"] | null;
            /**
             * Matchnumber
             * @default 0
             */
            matchNumber: number;
            /** Participants */
            participants: components["schemas"]["ParticipantSnapshot"][];
            /**
             * Phase
             * @enum {string}
             */
            phase: "lobby" | "playing" | "post_match";
            /** Postmatchdeadlineat */
            postMatchDeadlineAt?: number | null;
            result?: components["schemas"]["MatchResult"] | null;
            /** Revision */
            revision: number;
            /** Roomcode */
            roomCode: string;
            /** Scoreboard */
            scoreboard?: components["schemas"]["ParticipantScore"][];
            /** Seats */
            seats?: components["schemas"]["TableSeatSnapshot"][];
            /** Turndeadlineat */
            turnDeadlineAt?: number | null;
            /** Viewerseatindex */
            viewerSeatIndex: number;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * Cardpenalty
             * @default 0
             */
            cardPenalty: number;
            /**
             * Collectionbonus
             * @default 0
             */
            collectionBonus: number;
            /**
             * Correctbase
             * @default 0
             */
            correctBase: number;
            /**
             * Missedpenalty
             * @default 0
             */
            missedPenalty: number;
            /**
             * Speedbonus
             * @default 0
             */
            speedBonus: number;
            /**
             * Streakbonus
             * @default 0
             */
            streakBonus: number;
            /**
             * Wrongpenalty
             * @default 0
             */
            wrongPenalty: number;
        };
        /** TableSeatSnapshot */
        TableSeatSnapshot: {
            /**
             * Faceupcardcount
             * @default 0
             */
            faceUpCardCount: number;
            /** Seatindex */
            seatIndex: number;
            topCard?: components["schemas"]["CardSnapshot"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_room_api_v1_rooms_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_room_snapshot_api_v1_rooms__room_code__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                room_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    join_room_api_v1_rooms__room_code__participants_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                room_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
