name: halligalli
region: ams
services:
  - name: web
    image:
      registry_type: GHCR
      registry: optiplex331
      repository: halligalli-bossyang
      tag: latest # production_halligalli-web
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    envs:
      - key: NODE_ENV
        value: production
      - key: APP_VERSION
        value: local
      - key: COMMIT_SHA
        value: unknown
