name: halligalli
region: ams
services:
  - name: web
    github:
      repo: optiplex331/Halligalli-BossYang
      branch: master
      deploy_on_push: true
    build_command: npm install -g pnpm@11.0.9 && pnpm install --frozen-lockfile && pnpm run build
    run_command: node server/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    envs:
      - key: NODE_ENV
        value: production
