name: halligalli
region: ams
services:
- name: web
  image:
    registry_type: GHCR
    registry: optiplex331
    repository: halligalli-bossyang
    digest: sha256:1a73be44170a112c1a50b2234bcb4cdcb6368fc2d220d16569428a72aea4b8f3
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  http_port: 3001
  envs:
  - key: NODE_ENV
    value: production
  - key: APP_VERSION
    value: 0.3.0
  - key: COMMIT_SHA
    value: e9b2b6eed02a21b6f037b7ae514d3387ba94c298
