name: halligalli
region: ams
services:
  - name: web
    image:
      registry_type: GHCR
      registry: optiplex331
      repository: halligalli-bossyang
      digest: sha256:7487de8666c7ab8cd342b90ee55863f96f51211cc796be9c2173df3cc3e2dfc1
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    envs:
      - key: NODE_ENV
        value: production
      - key: APP_VERSION
        value: 0.1.0-0002-gb051852
      - key: COMMIT_SHA
        value: b051852b28e1f2bd2f8e5f64d0d142a3d5abe63c
