name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.HALLIGALLI_RELEASE_BOT_TOKEN }}
          config-file: .github/utils/release-please-config.json
          manifest-file: .github/utils/.release-please-manifest.json
          target-branch: master
